// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ggezchain/trade/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_af22ba7e83aace9b, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_af22ba7e83aace9b, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryGetTradeIndexRequest struct {
}

func (m *QueryGetTradeIndexRequest) Reset()         { *m = QueryGetTradeIndexRequest{} }
func (m *QueryGetTradeIndexRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetTradeIndexRequest) ProtoMessage()    {}
func (*QueryGetTradeIndexRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_af22ba7e83aace9b, []int{2}
}
func (m *QueryGetTradeIndexRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetTradeIndexRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetTradeIndexRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetTradeIndexRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetTradeIndexRequest.Merge(m, src)
}
func (m *QueryGetTradeIndexRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetTradeIndexRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetTradeIndexRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetTradeIndexRequest proto.InternalMessageInfo

type QueryGetTradeIndexResponse struct {
	TradeIndex TradeIndex `protobuf:"bytes,1,opt,name=TradeIndex,proto3" json:"TradeIndex"`
}

func (m *QueryGetTradeIndexResponse) Reset()         { *m = QueryGetTradeIndexResponse{} }
func (m *QueryGetTradeIndexResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetTradeIndexResponse) ProtoMessage()    {}
func (*QueryGetTradeIndexResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_af22ba7e83aace9b, []int{3}
}
func (m *QueryGetTradeIndexResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetTradeIndexResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetTradeIndexResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetTradeIndexResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetTradeIndexResponse.Merge(m, src)
}
func (m *QueryGetTradeIndexResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetTradeIndexResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetTradeIndexResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetTradeIndexResponse proto.InternalMessageInfo

func (m *QueryGetTradeIndexResponse) GetTradeIndex() TradeIndex {
	if m != nil {
		return m.TradeIndex
	}
	return TradeIndex{}
}

type QueryGetStoredTradeRequest struct {
	TradeIndex uint64 `protobuf:"varint,1,opt,name=tradeIndex,proto3" json:"tradeIndex,omitempty"`
}

func (m *QueryGetStoredTradeRequest) Reset()         { *m = QueryGetStoredTradeRequest{} }
func (m *QueryGetStoredTradeRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetStoredTradeRequest) ProtoMessage()    {}
func (*QueryGetStoredTradeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_af22ba7e83aace9b, []int{4}
}
func (m *QueryGetStoredTradeRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetStoredTradeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetStoredTradeRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetStoredTradeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetStoredTradeRequest.Merge(m, src)
}
func (m *QueryGetStoredTradeRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetStoredTradeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetStoredTradeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetStoredTradeRequest proto.InternalMessageInfo

func (m *QueryGetStoredTradeRequest) GetTradeIndex() uint64 {
	if m != nil {
		return m.TradeIndex
	}
	return 0
}

type QueryGetStoredTradeResponse struct {
	StoredTrade StoredTrade `protobuf:"bytes,1,opt,name=storedTrade,proto3" json:"storedTrade"`
}

func (m *QueryGetStoredTradeResponse) Reset()         { *m = QueryGetStoredTradeResponse{} }
func (m *QueryGetStoredTradeResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetStoredTradeResponse) ProtoMessage()    {}
func (*QueryGetStoredTradeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_af22ba7e83aace9b, []int{5}
}
func (m *QueryGetStoredTradeResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetStoredTradeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetStoredTradeResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetStoredTradeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetStoredTradeResponse.Merge(m, src)
}
func (m *QueryGetStoredTradeResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetStoredTradeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetStoredTradeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetStoredTradeResponse proto.InternalMessageInfo

func (m *QueryGetStoredTradeResponse) GetStoredTrade() StoredTrade {
	if m != nil {
		return m.StoredTrade
	}
	return StoredTrade{}
}

type QueryAllStoredTradeRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllStoredTradeRequest) Reset()         { *m = QueryAllStoredTradeRequest{} }
func (m *QueryAllStoredTradeRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllStoredTradeRequest) ProtoMessage()    {}
func (*QueryAllStoredTradeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_af22ba7e83aace9b, []int{6}
}
func (m *QueryAllStoredTradeRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllStoredTradeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllStoredTradeRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllStoredTradeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllStoredTradeRequest.Merge(m, src)
}
func (m *QueryAllStoredTradeRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllStoredTradeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllStoredTradeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllStoredTradeRequest proto.InternalMessageInfo

func (m *QueryAllStoredTradeRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllStoredTradeResponse struct {
	StoredTrade []StoredTrade       `protobuf:"bytes,1,rep,name=storedTrade,proto3" json:"storedTrade"`
	Pagination  *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllStoredTradeResponse) Reset()         { *m = QueryAllStoredTradeResponse{} }
func (m *QueryAllStoredTradeResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllStoredTradeResponse) ProtoMessage()    {}
func (*QueryAllStoredTradeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_af22ba7e83aace9b, []int{7}
}
func (m *QueryAllStoredTradeResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllStoredTradeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllStoredTradeResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllStoredTradeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllStoredTradeResponse.Merge(m, src)
}
func (m *QueryAllStoredTradeResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllStoredTradeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllStoredTradeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllStoredTradeResponse proto.InternalMessageInfo

func (m *QueryAllStoredTradeResponse) GetStoredTrade() []StoredTrade {
	if m != nil {
		return m.StoredTrade
	}
	return nil
}

func (m *QueryAllStoredTradeResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "ggezchain.trade.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "ggezchain.trade.QueryParamsResponse")
	proto.RegisterType((*QueryGetTradeIndexRequest)(nil), "ggezchain.trade.QueryGetTradeIndexRequest")
	proto.RegisterType((*QueryGetTradeIndexResponse)(nil), "ggezchain.trade.QueryGetTradeIndexResponse")
	proto.RegisterType((*QueryGetStoredTradeRequest)(nil), "ggezchain.trade.QueryGetStoredTradeRequest")
	proto.RegisterType((*QueryGetStoredTradeResponse)(nil), "ggezchain.trade.QueryGetStoredTradeResponse")
	proto.RegisterType((*QueryAllStoredTradeRequest)(nil), "ggezchain.trade.QueryAllStoredTradeRequest")
	proto.RegisterType((*QueryAllStoredTradeResponse)(nil), "ggezchain.trade.QueryAllStoredTradeResponse")
}

func init() { proto.RegisterFile("ggezchain/trade/query.proto", fileDescriptor_af22ba7e83aace9b) }

var fileDescriptor_af22ba7e83aace9b = []byte{
	// 591 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x94, 0x41, 0x8b, 0xd3, 0x40,
	0x18, 0x86, 0x3b, 0x6b, 0x2d, 0x38, 0x05, 0xc5, 0x71, 0x41, 0x4d, 0x97, 0xa8, 0xe3, 0xe2, 0xae,
	0x55, 0x33, 0xee, 0x8a, 0x08, 0xa2, 0x87, 0x16, 0xb1, 0x78, 0xdb, 0xad, 0x9e, 0xbc, 0x94, 0x69,
	0x3b, 0xa4, 0x81, 0x26, 0x93, 0xcd, 0x4c, 0x65, 0x57, 0x11, 0xc1, 0x5f, 0x20, 0x08, 0xde, 0x3c,
	0xeb, 0xc1, 0x83, 0x3f, 0x63, 0x8f, 0x0b, 0x5e, 0x3c, 0x89, 0xb4, 0x82, 0x07, 0xff, 0x84, 0x64,
	0x32, 0xdd, 0x4c, 0x93, 0xb4, 0x16, 0x2f, 0x21, 0x99, 0xef, 0xfd, 0xbe, 0xf7, 0x99, 0xe4, 0x9d,
	0xc0, 0x9a, 0xeb, 0xb2, 0x97, 0xbd, 0x01, 0xf5, 0x02, 0x22, 0x23, 0xda, 0x67, 0x64, 0x6f, 0xc4,
	0xa2, 0x03, 0x27, 0x8c, 0xb8, 0xe4, 0xe8, 0xcc, 0x71, 0xd1, 0x51, 0x45, 0xeb, 0x2c, 0xf5, 0xbd,
	0x80, 0x13, 0x75, 0x4d, 0x34, 0xd6, 0xaa, 0xcb, 0x5d, 0xae, 0x6e, 0x49, 0x7c, 0xa7, 0x57, 0xd7,
	0x5c, 0xce, 0xdd, 0x21, 0x23, 0x34, 0xf4, 0x08, 0x0d, 0x02, 0x2e, 0xa9, 0xf4, 0x78, 0x20, 0x74,
	0xb5, 0xde, 0xe3, 0xc2, 0xe7, 0x82, 0x74, 0xa9, 0xd0, 0x86, 0xe4, 0xc5, 0x56, 0x97, 0x49, 0xba,
	0x45, 0x42, 0xea, 0x7a, 0x81, 0x12, 0x1f, 0x4f, 0xca, 0x00, 0x86, 0x34, 0xa2, 0xfe, 0x74, 0xd2,
	0x95, 0x6c, 0x55, 0x5d, 0x3b, 0x5e, 0xd0, 0x67, 0xfb, 0x5a, 0x82, 0xb3, 0x12, 0x21, 0x79, 0xc4,
	0xfa, 0x1d, 0xf5, 0x90, 0x68, 0xf0, 0x2a, 0x44, 0xbb, 0x31, 0xc6, 0x8e, 0x9a, 0xdd, 0x66, 0x7b,
	0x23, 0x26, 0x24, 0xde, 0x85, 0xe7, 0x66, 0x56, 0x45, 0xc8, 0x03, 0xc1, 0xd0, 0x7d, 0x58, 0x49,
	0x18, 0x2e, 0x80, 0xcb, 0x60, 0xb3, 0xba, 0x7d, 0xde, 0xc9, 0xbc, 0x26, 0x27, 0x69, 0x68, 0x9e,
	0x3a, 0xfc, 0x71, 0xa9, 0xf4, 0xf9, 0xf7, 0xd7, 0x3a, 0x68, 0xeb, 0x0e, 0x5c, 0x83, 0x17, 0xd5,
	0xc8, 0x16, 0x93, 0xcf, 0x62, 0xe9, 0x93, 0x18, 0x74, 0xea, 0xd7, 0x81, 0x56, 0x51, 0x51, 0xdb,
	0x36, 0x20, 0x4c, 0x57, 0xb5, 0x75, 0x2d, 0x67, 0x9d, 0x4a, 0x9a, 0xe5, 0xd8, 0xbe, 0x6d, 0x34,
	0xe1, 0x07, 0xa9, 0xc1, 0x53, 0xf5, 0x12, 0x54, 0x4d, 0xdb, 0x23, 0x1b, 0x42, 0x39, 0x6b, 0x50,
	0x6e, 0x1b, 0x2b, 0xb8, 0x07, 0x6b, 0x85, 0xdd, 0x9a, 0xef, 0x11, 0xac, 0x8a, 0x74, 0x59, 0x03,
	0xae, 0xe5, 0x00, 0x8d, 0x56, 0x4d, 0x68, 0xb6, 0xe1, 0xbe, 0x46, 0x6c, 0x0c, 0x87, 0x05, 0x88,
	0x8f, 0x21, 0x4c, 0x03, 0xa2, 0x2d, 0xae, 0x39, 0x49, 0x9a, 0x9c, 0x38, 0x4d, 0x4e, 0x12, 0x5f,
	0x9d, 0x26, 0x67, 0x87, 0xba, 0xd3, 0xde, 0xb6, 0xd1, 0x89, 0xbf, 0x00, 0xbd, 0x97, 0xac, 0xcd,
	0xbc, 0xbd, 0x9c, 0xf8, 0x8f, 0xbd, 0xa0, 0xd6, 0x0c, 0xed, 0x8a, 0xa2, 0xdd, 0xf8, 0x27, 0x6d,
	0x82, 0x60, 0xe2, 0x6e, 0xff, 0x29, 0xc3, 0x93, 0x0a, 0x17, 0xbd, 0x81, 0x95, 0x24, 0x5c, 0xe8,
	0x6a, 0x8e, 0x26, 0x9f, 0x60, 0x6b, 0x7d, 0xb1, 0x28, 0xb1, 0xc2, 0xf5, 0xb7, 0xdf, 0x7e, 0xbd,
	0x5f, 0x59, 0x47, 0x98, 0xf8, 0x7c, 0x24, 0xa8, 0xd7, 0x8d, 0xe8, 0x80, 0x14, 0x1f, 0x3b, 0xf4,
	0x01, 0x98, 0x31, 0x44, 0xf5, 0x62, 0x83, 0xa2, 0x78, 0x5b, 0x37, 0x96, 0xd2, 0x6a, 0x26, 0xa2,
	0x98, 0xae, 0xa3, 0x8d, 0x45, 0x4c, 0xc6, 0x61, 0x47, 0x9f, 0x00, 0xac, 0x1a, 0xdf, 0x03, 0xcd,
	0x77, 0xcb, 0xe7, 0xca, 0xba, 0xb9, 0x9c, 0x58, 0xb3, 0x3d, 0x54, 0x6c, 0xf7, 0xd0, 0xdd, 0x45,
	0x6c, 0xe6, 0x5f, 0x86, 0xbc, 0x4a, 0x8f, 0xd1, 0x6b, 0xf4, 0x11, 0xc0, 0xd3, 0xc6, 0xd8, 0xc6,
	0x70, 0x38, 0x0f, 0xb6, 0xf0, 0x10, 0xcc, 0x83, 0x2d, 0x8e, 0x32, 0xbe, 0xad, 0x60, 0xeb, 0x68,
	0x73, 0x59, 0xd8, 0x66, 0xeb, 0x70, 0x6c, 0x83, 0xa3, 0xb1, 0x0d, 0x7e, 0x8e, 0x6d, 0xf0, 0x6e,
	0x62, 0x97, 0x8e, 0x26, 0x76, 0xe9, 0xfb, 0xc4, 0x2e, 0x3d, 0xbf, 0xe5, 0x7a, 0x72, 0x30, 0xea,
	0x3a, 0x3d, 0xee, 0x17, 0x4f, 0xdb, 0x9f, 0x7e, 0x98, 0x83, 0x90, 0x89, 0x6e, 0x45, 0xfd, 0x5c,
	0xef, 0xfc, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x26, 0x77, 0xdb, 0x12, 0x64, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a TradeIndex by index.
	TradeIndex(ctx context.Context, in *QueryGetTradeIndexRequest, opts ...grpc.CallOption) (*QueryGetTradeIndexResponse, error)
	// Queries a list of StoredTrade items.
	StoredTrade(ctx context.Context, in *QueryGetStoredTradeRequest, opts ...grpc.CallOption) (*QueryGetStoredTradeResponse, error)
	StoredTradeAll(ctx context.Context, in *QueryAllStoredTradeRequest, opts ...grpc.CallOption) (*QueryAllStoredTradeResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/ggezchain.trade.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) TradeIndex(ctx context.Context, in *QueryGetTradeIndexRequest, opts ...grpc.CallOption) (*QueryGetTradeIndexResponse, error) {
	out := new(QueryGetTradeIndexResponse)
	err := c.cc.Invoke(ctx, "/ggezchain.trade.Query/TradeIndex", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) StoredTrade(ctx context.Context, in *QueryGetStoredTradeRequest, opts ...grpc.CallOption) (*QueryGetStoredTradeResponse, error) {
	out := new(QueryGetStoredTradeResponse)
	err := c.cc.Invoke(ctx, "/ggezchain.trade.Query/StoredTrade", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) StoredTradeAll(ctx context.Context, in *QueryAllStoredTradeRequest, opts ...grpc.CallOption) (*QueryAllStoredTradeResponse, error) {
	out := new(QueryAllStoredTradeResponse)
	err := c.cc.Invoke(ctx, "/ggezchain.trade.Query/StoredTradeAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a TradeIndex by index.
	TradeIndex(context.Context, *QueryGetTradeIndexRequest) (*QueryGetTradeIndexResponse, error)
	// Queries a list of StoredTrade items.
	StoredTrade(context.Context, *QueryGetStoredTradeRequest) (*QueryGetStoredTradeResponse, error)
	StoredTradeAll(context.Context, *QueryAllStoredTradeRequest) (*QueryAllStoredTradeResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) TradeIndex(ctx context.Context, req *QueryGetTradeIndexRequest) (*QueryGetTradeIndexResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TradeIndex not implemented")
}
func (*UnimplementedQueryServer) StoredTrade(ctx context.Context, req *QueryGetStoredTradeRequest) (*QueryGetStoredTradeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StoredTrade not implemented")
}
func (*UnimplementedQueryServer) StoredTradeAll(ctx context.Context, req *QueryAllStoredTradeRequest) (*QueryAllStoredTradeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StoredTradeAll not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ggezchain.trade.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_TradeIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetTradeIndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).TradeIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ggezchain.trade.Query/TradeIndex",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).TradeIndex(ctx, req.(*QueryGetTradeIndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_StoredTrade_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetStoredTradeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).StoredTrade(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ggezchain.trade.Query/StoredTrade",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).StoredTrade(ctx, req.(*QueryGetStoredTradeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_StoredTradeAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllStoredTradeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).StoredTradeAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ggezchain.trade.Query/StoredTradeAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).StoredTradeAll(ctx, req.(*QueryAllStoredTradeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ggezchain.trade.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "TradeIndex",
			Handler:    _Query_TradeIndex_Handler,
		},
		{
			MethodName: "StoredTrade",
			Handler:    _Query_StoredTrade_Handler,
		},
		{
			MethodName: "StoredTradeAll",
			Handler:    _Query_StoredTradeAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ggezchain/trade/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetTradeIndexRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetTradeIndexRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetTradeIndexRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryGetTradeIndexResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetTradeIndexResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetTradeIndexResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.TradeIndex.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetStoredTradeRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetStoredTradeRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetStoredTradeRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.TradeIndex != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.TradeIndex))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetStoredTradeResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetStoredTradeResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetStoredTradeResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.StoredTrade.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllStoredTradeRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllStoredTradeRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllStoredTradeRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllStoredTradeResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllStoredTradeResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllStoredTradeResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.StoredTrade) > 0 {
		for iNdEx := len(m.StoredTrade) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.StoredTrade[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetTradeIndexRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryGetTradeIndexResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.TradeIndex.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetStoredTradeRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.TradeIndex != 0 {
		n += 1 + sovQuery(uint64(m.TradeIndex))
	}
	return n
}

func (m *QueryGetStoredTradeResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.StoredTrade.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllStoredTradeRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllStoredTradeResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.StoredTrade) > 0 {
		for _, e := range m.StoredTrade {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetTradeIndexRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetTradeIndexRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetTradeIndexRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetTradeIndexResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetTradeIndexResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetTradeIndexResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TradeIndex", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TradeIndex.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetStoredTradeRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetStoredTradeRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetStoredTradeRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TradeIndex", wireType)
			}
			m.TradeIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TradeIndex |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetStoredTradeResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetStoredTradeResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetStoredTradeResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StoredTrade", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.StoredTrade.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllStoredTradeRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllStoredTradeRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllStoredTradeRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllStoredTradeResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllStoredTradeResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllStoredTradeResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StoredTrade", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StoredTrade = append(m.StoredTrade, StoredTrade{})
			if err := m.StoredTrade[len(m.StoredTrade)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
