// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ggezchain/trade/stored_trade.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type StoredTrade struct {
	TradeIndex      uint64 `protobuf:"varint,1,opt,name=tradeIndex,proto3" json:"tradeIndex,omitempty"`
	TradeType       string `protobuf:"bytes,2,opt,name=tradeType,proto3" json:"tradeType,omitempty"`
	Coin            string `protobuf:"bytes,3,opt,name=coin,proto3" json:"coin,omitempty"`
	Price           string `protobuf:"bytes,4,opt,name=price,proto3" json:"price,omitempty"`
	Quantity        string `protobuf:"bytes,5,opt,name=quantity,proto3" json:"quantity,omitempty"`
	ReceiverAddress string `protobuf:"bytes,6,opt,name=receiverAddress,proto3" json:"receiverAddress,omitempty"`
	Status          string `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	Maker           string `protobuf:"bytes,8,opt,name=maker,proto3" json:"maker,omitempty"`
	Checker         string `protobuf:"bytes,9,opt,name=checker,proto3" json:"checker,omitempty"`
	CreateDate      string `protobuf:"bytes,10,opt,name=createDate,proto3" json:"createDate,omitempty"`
	UpdateDate      string `protobuf:"bytes,11,opt,name=updateDate,proto3" json:"updateDate,omitempty"`
	ProcessDate     string `protobuf:"bytes,12,opt,name=processDate,proto3" json:"processDate,omitempty"`
	TradeData       string `protobuf:"bytes,13,opt,name=tradeData,proto3" json:"tradeData,omitempty"`
	Result          string `protobuf:"bytes,14,opt,name=result,proto3" json:"result,omitempty"`
}

func (m *StoredTrade) Reset()         { *m = StoredTrade{} }
func (m *StoredTrade) String() string { return proto.CompactTextString(m) }
func (*StoredTrade) ProtoMessage()    {}
func (*StoredTrade) Descriptor() ([]byte, []int) {
	return fileDescriptor_4cbf8bf5cc0260cd, []int{0}
}
func (m *StoredTrade) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *StoredTrade) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_StoredTrade.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *StoredTrade) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoredTrade.Merge(m, src)
}
func (m *StoredTrade) XXX_Size() int {
	return m.Size()
}
func (m *StoredTrade) XXX_DiscardUnknown() {
	xxx_messageInfo_StoredTrade.DiscardUnknown(m)
}

var xxx_messageInfo_StoredTrade proto.InternalMessageInfo

func (m *StoredTrade) GetTradeIndex() uint64 {
	if m != nil {
		return m.TradeIndex
	}
	return 0
}

func (m *StoredTrade) GetTradeType() string {
	if m != nil {
		return m.TradeType
	}
	return ""
}

func (m *StoredTrade) GetCoin() string {
	if m != nil {
		return m.Coin
	}
	return ""
}

func (m *StoredTrade) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

func (m *StoredTrade) GetQuantity() string {
	if m != nil {
		return m.Quantity
	}
	return ""
}

func (m *StoredTrade) GetReceiverAddress() string {
	if m != nil {
		return m.ReceiverAddress
	}
	return ""
}

func (m *StoredTrade) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *StoredTrade) GetMaker() string {
	if m != nil {
		return m.Maker
	}
	return ""
}

func (m *StoredTrade) GetChecker() string {
	if m != nil {
		return m.Checker
	}
	return ""
}

func (m *StoredTrade) GetCreateDate() string {
	if m != nil {
		return m.CreateDate
	}
	return ""
}

func (m *StoredTrade) GetUpdateDate() string {
	if m != nil {
		return m.UpdateDate
	}
	return ""
}

func (m *StoredTrade) GetProcessDate() string {
	if m != nil {
		return m.ProcessDate
	}
	return ""
}

func (m *StoredTrade) GetTradeData() string {
	if m != nil {
		return m.TradeData
	}
	return ""
}

func (m *StoredTrade) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func init() {
	proto.RegisterType((*StoredTrade)(nil), "ggezchain.trade.StoredTrade")
}

func init() {
	proto.RegisterFile("ggezchain/trade/stored_trade.proto", fileDescriptor_4cbf8bf5cc0260cd)
}

var fileDescriptor_4cbf8bf5cc0260cd = []byte{
	// 342 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x92, 0xbf, 0x4e, 0xc3, 0x30,
	0x10, 0xc6, 0x1b, 0xfa, 0xdf, 0x05, 0x2a, 0x59, 0x08, 0x59, 0x08, 0x59, 0x55, 0xa7, 0x4e, 0xc9,
	0xc0, 0x13, 0x80, 0x3a, 0xc0, 0x5a, 0x3a, 0xb1, 0x20, 0xd7, 0x39, 0x35, 0x16, 0x34, 0x0e, 0xb6,
	0x83, 0x5a, 0x9e, 0x82, 0x9d, 0x17, 0x62, 0xec, 0xc8, 0x88, 0x9a, 0x17, 0x41, 0xbe, 0xb4, 0x69,
	0xc4, 0x96, 0xdf, 0xef, 0xfb, 0x24, 0xeb, 0xee, 0x42, 0xc6, 0xcb, 0x25, 0x7c, 0xc8, 0x44, 0xa8,
	0x34, 0x72, 0x46, 0xc4, 0x10, 0x59, 0xa7, 0x0d, 0xc4, 0xcf, 0x08, 0x61, 0x66, 0xb4, 0xd3, 0x74,
	0x58, 0x75, 0x42, 0xd4, 0xe3, 0xaf, 0x26, 0x19, 0x3c, 0x62, 0x6f, 0xee, 0x99, 0x72, 0x42, 0x30,
	0x78, 0x48, 0x63, 0x58, 0xb3, 0x60, 0x14, 0x4c, 0x5a, 0xb3, 0x9a, 0xa1, 0xd7, 0xa4, 0x8f, 0x34,
	0xdf, 0x64, 0xc0, 0x4e, 0x46, 0xc1, 0xa4, 0x3f, 0x3b, 0x0a, 0x4a, 0x49, 0x4b, 0x6a, 0x95, 0xb2,
	0x26, 0x06, 0xf8, 0x4d, 0x2f, 0x48, 0x3b, 0x33, 0x4a, 0x02, 0x6b, 0xa1, 0x2c, 0x81, 0x5e, 0x91,
	0xde, 0x5b, 0x2e, 0x52, 0xa7, 0xdc, 0x86, 0xb5, 0x31, 0xa8, 0x98, 0x4e, 0xc8, 0xd0, 0x80, 0x04,
	0xf5, 0x0e, 0xe6, 0x36, 0x8e, 0x0d, 0x58, 0xcb, 0x3a, 0x58, 0xf9, 0xaf, 0xe9, 0x25, 0xe9, 0x58,
	0x27, 0x5c, 0x6e, 0x59, 0x17, 0x0b, 0x7b, 0xf2, 0x6f, 0xae, 0xc4, 0x0b, 0x18, 0xd6, 0x2b, 0xdf,
	0x44, 0xa0, 0x8c, 0x74, 0x65, 0x02, 0xd2, 0xfb, 0x3e, 0xfa, 0x03, 0xfa, 0xa9, 0xa5, 0x01, 0xe1,
	0x60, 0x2a, 0x1c, 0x30, 0x82, 0x61, 0xcd, 0xf8, 0x3c, 0xcf, 0xe2, 0x43, 0x3e, 0x28, 0xf3, 0xa3,
	0xa1, 0x23, 0x32, 0xc8, 0x8c, 0x96, 0x60, 0x2d, 0x16, 0x4e, 0xb1, 0x50, 0x57, 0xd5, 0xde, 0xa6,
	0xc2, 0x09, 0x76, 0x56, 0xdb, 0x9b, 0x17, 0x7e, 0x0e, 0x03, 0x36, 0x7f, 0x75, 0xec, 0xbc, 0x9c,
	0xa3, 0xa4, 0xbb, 0xfb, 0xef, 0x1d, 0x0f, 0xb6, 0x3b, 0x1e, 0xfc, 0xee, 0x78, 0xf0, 0x59, 0xf0,
	0xc6, 0xb6, 0xe0, 0x8d, 0x9f, 0x82, 0x37, 0x9e, 0xc2, 0xa5, 0x72, 0x49, 0xbe, 0x08, 0xa5, 0x5e,
	0x45, 0x2b, 0x9d, 0x5b, 0xa1, 0x16, 0x46, 0x24, 0x51, 0x75, 0x5e, 0x1b, 0xad, 0xf7, 0x7f, 0x81,
	0xdb, 0x64, 0x60, 0x17, 0x1d, 0xbc, 0xff, 0xcd, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x83, 0x2a,
	0x05, 0xac, 0x25, 0x02, 0x00, 0x00,
}

func (m *StoredTrade) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StoredTrade) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *StoredTrade) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Result) > 0 {
		i -= len(m.Result)
		copy(dAtA[i:], m.Result)
		i = encodeVarintStoredTrade(dAtA, i, uint64(len(m.Result)))
		i--
		dAtA[i] = 0x72
	}
	if len(m.TradeData) > 0 {
		i -= len(m.TradeData)
		copy(dAtA[i:], m.TradeData)
		i = encodeVarintStoredTrade(dAtA, i, uint64(len(m.TradeData)))
		i--
		dAtA[i] = 0x6a
	}
	if len(m.ProcessDate) > 0 {
		i -= len(m.ProcessDate)
		copy(dAtA[i:], m.ProcessDate)
		i = encodeVarintStoredTrade(dAtA, i, uint64(len(m.ProcessDate)))
		i--
		dAtA[i] = 0x62
	}
	if len(m.UpdateDate) > 0 {
		i -= len(m.UpdateDate)
		copy(dAtA[i:], m.UpdateDate)
		i = encodeVarintStoredTrade(dAtA, i, uint64(len(m.UpdateDate)))
		i--
		dAtA[i] = 0x5a
	}
	if len(m.CreateDate) > 0 {
		i -= len(m.CreateDate)
		copy(dAtA[i:], m.CreateDate)
		i = encodeVarintStoredTrade(dAtA, i, uint64(len(m.CreateDate)))
		i--
		dAtA[i] = 0x52
	}
	if len(m.Checker) > 0 {
		i -= len(m.Checker)
		copy(dAtA[i:], m.Checker)
		i = encodeVarintStoredTrade(dAtA, i, uint64(len(m.Checker)))
		i--
		dAtA[i] = 0x4a
	}
	if len(m.Maker) > 0 {
		i -= len(m.Maker)
		copy(dAtA[i:], m.Maker)
		i = encodeVarintStoredTrade(dAtA, i, uint64(len(m.Maker)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.Status) > 0 {
		i -= len(m.Status)
		copy(dAtA[i:], m.Status)
		i = encodeVarintStoredTrade(dAtA, i, uint64(len(m.Status)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.ReceiverAddress) > 0 {
		i -= len(m.ReceiverAddress)
		copy(dAtA[i:], m.ReceiverAddress)
		i = encodeVarintStoredTrade(dAtA, i, uint64(len(m.ReceiverAddress)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Quantity) > 0 {
		i -= len(m.Quantity)
		copy(dAtA[i:], m.Quantity)
		i = encodeVarintStoredTrade(dAtA, i, uint64(len(m.Quantity)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Price) > 0 {
		i -= len(m.Price)
		copy(dAtA[i:], m.Price)
		i = encodeVarintStoredTrade(dAtA, i, uint64(len(m.Price)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Coin) > 0 {
		i -= len(m.Coin)
		copy(dAtA[i:], m.Coin)
		i = encodeVarintStoredTrade(dAtA, i, uint64(len(m.Coin)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.TradeType) > 0 {
		i -= len(m.TradeType)
		copy(dAtA[i:], m.TradeType)
		i = encodeVarintStoredTrade(dAtA, i, uint64(len(m.TradeType)))
		i--
		dAtA[i] = 0x12
	}
	if m.TradeIndex != 0 {
		i = encodeVarintStoredTrade(dAtA, i, uint64(m.TradeIndex))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintStoredTrade(dAtA []byte, offset int, v uint64) int {
	offset -= sovStoredTrade(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *StoredTrade) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.TradeIndex != 0 {
		n += 1 + sovStoredTrade(uint64(m.TradeIndex))
	}
	l = len(m.TradeType)
	if l > 0 {
		n += 1 + l + sovStoredTrade(uint64(l))
	}
	l = len(m.Coin)
	if l > 0 {
		n += 1 + l + sovStoredTrade(uint64(l))
	}
	l = len(m.Price)
	if l > 0 {
		n += 1 + l + sovStoredTrade(uint64(l))
	}
	l = len(m.Quantity)
	if l > 0 {
		n += 1 + l + sovStoredTrade(uint64(l))
	}
	l = len(m.ReceiverAddress)
	if l > 0 {
		n += 1 + l + sovStoredTrade(uint64(l))
	}
	l = len(m.Status)
	if l > 0 {
		n += 1 + l + sovStoredTrade(uint64(l))
	}
	l = len(m.Maker)
	if l > 0 {
		n += 1 + l + sovStoredTrade(uint64(l))
	}
	l = len(m.Checker)
	if l > 0 {
		n += 1 + l + sovStoredTrade(uint64(l))
	}
	l = len(m.CreateDate)
	if l > 0 {
		n += 1 + l + sovStoredTrade(uint64(l))
	}
	l = len(m.UpdateDate)
	if l > 0 {
		n += 1 + l + sovStoredTrade(uint64(l))
	}
	l = len(m.ProcessDate)
	if l > 0 {
		n += 1 + l + sovStoredTrade(uint64(l))
	}
	l = len(m.TradeData)
	if l > 0 {
		n += 1 + l + sovStoredTrade(uint64(l))
	}
	l = len(m.Result)
	if l > 0 {
		n += 1 + l + sovStoredTrade(uint64(l))
	}
	return n
}

func sovStoredTrade(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozStoredTrade(x uint64) (n int) {
	return sovStoredTrade(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *StoredTrade) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowStoredTrade
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StoredTrade: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StoredTrade: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TradeIndex", wireType)
			}
			m.TradeIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStoredTrade
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TradeIndex |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TradeType", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStoredTrade
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStoredTrade
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStoredTrade
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TradeType = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Coin", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStoredTrade
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStoredTrade
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStoredTrade
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Coin = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Price", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStoredTrade
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStoredTrade
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStoredTrade
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Price = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Quantity", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStoredTrade
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStoredTrade
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStoredTrade
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Quantity = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReceiverAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStoredTrade
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStoredTrade
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStoredTrade
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ReceiverAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStoredTrade
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStoredTrade
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStoredTrade
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Status = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Maker", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStoredTrade
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStoredTrade
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStoredTrade
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Maker = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Checker", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStoredTrade
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStoredTrade
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStoredTrade
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Checker = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreateDate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStoredTrade
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStoredTrade
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStoredTrade
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CreateDate = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdateDate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStoredTrade
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStoredTrade
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStoredTrade
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UpdateDate = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProcessDate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStoredTrade
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStoredTrade
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStoredTrade
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ProcessDate = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TradeData", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStoredTrade
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStoredTrade
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStoredTrade
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TradeData = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 14:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Result", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStoredTrade
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStoredTrade
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStoredTrade
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Result = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipStoredTrade(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthStoredTrade
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipStoredTrade(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowStoredTrade
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowStoredTrade
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowStoredTrade
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthStoredTrade
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupStoredTrade
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthStoredTrade
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthStoredTrade        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowStoredTrade          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupStoredTrade = fmt.Errorf("proto: unexpected end of group")
)
